# Generated by Django 2.2.5 on 2022-11-03 20:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('Name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('Platform', models.CharField(choices=[('Board Game', 'Board_Game'), ('PlayStation', 'PlayStation'), ('Nintendo', 'Nintendo'), ('PC', 'PC'), ('Puzzle', 'Puzzle'), ('XBox', 'XBox'), ('Other', 'Other')], max_length=40)),
                ('Rating', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=100)),
                ('Notes', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            managers=[
                ('GameModel', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('Name', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('Thumb', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
            managers=[
                ('WishListModelMgr', django.db.models.manager.Manager()),
            ],
        ),
    ]
