# Generated by Django 4.1.2 on 2022-10-13 06:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=60)),
                ('Starting_Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_Transaction', models.DateField(auto_now_add=True)),
                ('Type_of_Transaction', models.CharField(choices=[('Withdrawl', 'Withdrawl'), ('Deposit', 'Deposit')], max_length=60)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('Description', models.TextField(blank=True, default='', max_length=300)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Checkbook.account')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
