# Generated by Django 4.1.2 on 2022-10-14 02:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type_of_Transaction',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawl', 'Withdrawl')], max_length=60),
        ),
    ]
