# Generated by Django 4.1.2 on 2022-10-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0002_alter_account_managers_alter_transaction_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Type_of_Transaction',
            field=models.CharField(choices=[('Withdrawl', 'Withdrawl'), ('Deposit', 'Deposit')], max_length=60),
        ),
    ]
