# Generated by Django 4.1.2 on 2022-10-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0005_alter_account_managers_alter_transaction_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Account',
            new_name='account',
        ),
    ]
